name: Watch

on:
  schedule:
    - cron: '30 */4 * * *'
  push:
    branches: ['master']

jobs:
  docker:
    name: Push tagged docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Dockerfile with latest version
        id: fetch_version
        run: |
          last=$(curl -s https://packagist.org/packages/vimeo/psalm.json|jq '[.package.versions[]|select(.version|test("^\\d+\\.\\d+\\.\\d+$"))|.version]|max_by(.|[splits("[.]")]|map(tonumber))')
          last=$(echo $last | tr -d '"')
          echo "Last Psalm version is $last"
          echo ::set-output name=last::$last

          sed -i -re "s/require vimeo\/psalm/require vimeo\/psalm:$last/" Dockerfile
          cat Dockerfile

      - name: Build images
        run: docker build -t ghcr.io/psalm/psalm-security-scan:${{ steps.fetch_version.outputs.last }} -t ghcr.io/psalm/psalm-security-scan:latest .

      - name: Publish
        run: |
          docker push ghcr.io/psalm/psalm-security-scan:${{ steps.fetch_version.outputs.last }}
          docker push ghcr.io/psalm/psalm-security-scan:latest
